/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CreateAcademyRouteImport } from './routes/create-academy'
import { Route as AcademySelectionRouteImport } from './routes/academy-selection'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AcademiesIndexRouteImport } from './routes/academies/index'
import { Route as PublicCoursesRouteImport } from './routes/public/courses'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as AcademiesSlugRouteImport } from './routes/academies/$slug'
import { Route as AuthenticatedRedeemCodeRouteImport } from './routes/_authenticated/redeem-code'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedLearningPathsRouteImport } from './routes/_authenticated/learning-paths'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpSuccessRouteImport } from './routes/(auth)/sign-up-success'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authConfirmRouteImport } from './routes/(auth)/confirm'
import { Route as AuthenticatedSuperAdminRouteRouteImport } from './routes/_authenticated/super-admin/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as PublicCoursesCourseSlugRouteImport } from './routes/public/courses/$courseSlug'
import { Route as PublicAcademiesAcademySlugRouteImport } from './routes/public/academies/$academySlug'
import { Route as AuthenticatedSuperAdminCategoriesRouteImport } from './routes/_authenticated/super-admin/categories'
import { Route as AuthenticatedSuperAdminAcademiesRouteImport } from './routes/_authenticated/super-admin/academies'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAdminLearningPathsRouteImport } from './routes/_authenticated/admin/learning-paths'
import { Route as AuthenticatedSuperAdminGamificationIndexRouteImport } from './routes/_authenticated/super-admin/gamification/index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin/courses/index'
import { Route as AuthenticatedAcademyAcademySlugDashboardRouteImport } from './routes/_authenticated/academy/$academySlug/dashboard'
import { Route as AuthenticatedAcademyAcademySlugCoursesIndexRouteImport } from './routes/_authenticated/academy/$academySlug/courses/index'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/route'
import { Route as AuthenticatedAdminCoursesCourseIdManageIndexRouteImport } from './routes/_authenticated/admin/courses/$courseId/manage/index'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/index'
import { Route as AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRouteImport } from './routes/_authenticated/super-admin/gamification/academies/$slug/badges'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/students'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/settings'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/lessons'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/info'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/exams'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/certificates'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/assignments'
import { Route as AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRouteImport } from './routes/_authenticated/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions/index'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAcademyRoute = CreateAcademyRouteImport.update({
  id: '/create-academy',
  path: '/create-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySelectionRoute = AcademySelectionRouteImport.update({
  id: '/academy-selection',
  path: '/academy-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesIndexRoute = AcademiesIndexRouteImport.update({
  id: '/academies/',
  path: '/academies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/public/courses',
  path: '/public/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesSlugRoute = AcademiesSlugRouteImport.update({
  id: '/academies/$slug',
  path: '/academies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRedeemCodeRoute = AuthenticatedRedeemCodeRouteImport.update({
  id: '/redeem-code',
  path: '/redeem-code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningPathsRoute =
  AuthenticatedLearningPathsRouteImport.update({
    id: '/learning-paths',
    path: '/learning-paths',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpSuccessRoute = authSignUpSuccessRouteImport.update({
  id: '/(auth)/sign-up-success',
  path: '/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmRoute = authConfirmRouteImport.update({
  id: '/(auth)/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuperAdminRouteRoute =
  AuthenticatedSuperAdminRouteRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicCoursesCourseSlugRoute = PublicCoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => PublicCoursesRoute,
} as any)
const PublicAcademiesAcademySlugRoute =
  PublicAcademiesAcademySlugRouteImport.update({
    id: '/public/academies/$academySlug',
    path: '/public/academies/$academySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedSuperAdminCategoriesRoute =
  AuthenticatedSuperAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminAcademiesRoute =
  AuthenticatedSuperAdminAcademiesRouteImport.update({
    id: '/academies',
    path: '/academies',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminLearningPathsRoute =
  AuthenticatedAdminLearningPathsRouteImport.update({
    id: '/learning-paths',
    path: '/learning-paths',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedSuperAdminGamificationIndexRoute =
  AuthenticatedSuperAdminGamificationIndexRouteImport.update({
    id: '/gamification/',
    path: '/gamification/',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugDashboardRoute =
  AuthenticatedAcademyAcademySlugDashboardRouteImport.update({
    id: '/academy/$academySlug/dashboard',
    path: '/academy/$academySlug/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesIndexRoute =
  AuthenticatedAcademyAcademySlugCoursesIndexRouteImport.update({
    id: '/academy/$academySlug/courses/',
    path: '/academy/$academySlug/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteImport.update({
    id: '/academy/$academySlug/courses/$courseSlug',
    path: '/academy/$academySlug/courses/$courseSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdManageIndexRoute =
  AuthenticatedAdminCoursesCourseIdManageIndexRouteImport.update({
    id: '/courses/$courseId/manage/',
    path: '/courses/$courseId/manage/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute =
  AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRouteImport.update({
    id: '/gamification/academies/$slug/badges',
    path: '/gamification/academies/$slug/badges',
    getParentRoute: () => AuthenticatedSuperAdminRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRouteImport.update({
    id: '/info',
    path: '/info',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRouteImport.update({
    id: '/exams',
    path: '/exams',
    getParentRoute: () =>
      AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
  } as any)
const AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRouteImport.update(
    {
      id: '/certificates',
      path: '/certificates',
      getParentRoute: () =>
        AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
    } as any,
  )
const AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRouteImport.update(
    {
      id: '/assignments',
      path: '/assignments',
      getParentRoute: () =>
        AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
    } as any,
  )
const AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRouteImport.update(
    {
      id: '/assessments/$assessmentId/questions/',
      path: '/assessments/$assessmentId/questions/',
      getParentRoute: () =>
        AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning-paths': typeof AuthenticatedLearningPathsRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/redeem-code': typeof AuthenticatedRedeemCodeRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies': typeof AcademiesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/learning-paths': typeof AuthenticatedAdminLearningPathsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/super-admin/academies': typeof AuthenticatedSuperAdminAcademiesRoute
  '/super-admin/categories': typeof AuthenticatedSuperAdminCategoriesRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academy/$academySlug/dashboard': typeof AuthenticatedAcademyAcademySlugDashboardRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/super-admin/gamification': typeof AuthenticatedSuperAdminGamificationIndexRoute
  '/academy/$academySlug/courses/$courseSlug': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteWithChildren
  '/academy/$academySlug/courses': typeof AuthenticatedAcademyAcademySlugCoursesIndexRoute
  '/academy/$academySlug/courses/$courseSlug/assignments': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute
  '/academy/$academySlug/courses/$courseSlug/certificates': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute
  '/academy/$academySlug/courses/$courseSlug/exams': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute
  '/academy/$academySlug/courses/$courseSlug/info': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute
  '/academy/$academySlug/courses/$courseSlug/lessons': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute
  '/academy/$academySlug/courses/$courseSlug/settings': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute
  '/academy/$academySlug/courses/$courseSlug/students': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute
  '/super-admin/gamification/academies/$slug/badges': typeof AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute
  '/academy/$academySlug/courses/$courseSlug/': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute
  '/admin/courses/$courseId/manage': typeof AuthenticatedAdminCoursesCourseIdManageIndexRoute
  '/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning-paths': typeof AuthenticatedLearningPathsRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/redeem-code': typeof AuthenticatedRedeemCodeRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies': typeof AcademiesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/learning-paths': typeof AuthenticatedAdminLearningPathsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/super-admin/academies': typeof AuthenticatedSuperAdminAcademiesRoute
  '/super-admin/categories': typeof AuthenticatedSuperAdminCategoriesRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academy/$academySlug/dashboard': typeof AuthenticatedAcademyAcademySlugDashboardRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/super-admin/gamification': typeof AuthenticatedSuperAdminGamificationIndexRoute
  '/academy/$academySlug/courses': typeof AuthenticatedAcademyAcademySlugCoursesIndexRoute
  '/academy/$academySlug/courses/$courseSlug/assignments': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute
  '/academy/$academySlug/courses/$courseSlug/certificates': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute
  '/academy/$academySlug/courses/$courseSlug/exams': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute
  '/academy/$academySlug/courses/$courseSlug/info': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute
  '/academy/$academySlug/courses/$courseSlug/lessons': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute
  '/academy/$academySlug/courses/$courseSlug/settings': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute
  '/academy/$academySlug/courses/$courseSlug/students': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute
  '/super-admin/gamification/academies/$slug/badges': typeof AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute
  '/academy/$academySlug/courses/$courseSlug': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute
  '/admin/courses/$courseId/manage': typeof AuthenticatedAdminCoursesCourseIdManageIndexRoute
  '/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/super-admin': typeof AuthenticatedSuperAdminRouteRouteWithChildren
  '/(auth)/confirm': typeof authConfirmRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-up-success': typeof authSignUpSuccessRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learning-paths': typeof AuthenticatedLearningPathsRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/redeem-code': typeof AuthenticatedRedeemCodeRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies/': typeof AcademiesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/learning-paths': typeof AuthenticatedAdminLearningPathsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/super-admin/academies': typeof AuthenticatedSuperAdminAcademiesRoute
  '/_authenticated/super-admin/categories': typeof AuthenticatedSuperAdminCategoriesRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/academy/$academySlug/dashboard': typeof AuthenticatedAcademyAcademySlugDashboardRoute
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/super-admin/gamification/': typeof AuthenticatedSuperAdminGamificationIndexRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteWithChildren
  '/_authenticated/academy/$academySlug/courses/': typeof AuthenticatedAcademyAcademySlugCoursesIndexRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/assignments': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/certificates': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/exams': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/info': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/lessons': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/settings': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/students': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute
  '/_authenticated/super-admin/gamification/academies/$slug/badges': typeof AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute
  '/_authenticated/admin/courses/$courseId/manage/': typeof AuthenticatedAdminCoursesCourseIdManageIndexRoute
  '/_authenticated/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions/': typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/admin'
    | '/settings'
    | '/super-admin'
    | '/confirm'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/sign-up-success'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/learning-paths'
    | '/my-courses'
    | '/onboarding'
    | '/redeem-code'
    | '/academies/$slug'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies'
    | '/courses'
    | '/admin/learning-paths'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/super-admin/academies'
    | '/super-admin/categories'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/academy/$academySlug/dashboard'
    | '/admin/courses'
    | '/super-admin/gamification'
    | '/academy/$academySlug/courses/$courseSlug'
    | '/academy/$academySlug/courses'
    | '/academy/$academySlug/courses/$courseSlug/assignments'
    | '/academy/$academySlug/courses/$courseSlug/certificates'
    | '/academy/$academySlug/courses/$courseSlug/exams'
    | '/academy/$academySlug/courses/$courseSlug/info'
    | '/academy/$academySlug/courses/$courseSlug/lessons'
    | '/academy/$academySlug/courses/$courseSlug/settings'
    | '/academy/$academySlug/courses/$courseSlug/students'
    | '/super-admin/gamification/academies/$slug/badges'
    | '/academy/$academySlug/courses/$courseSlug/'
    | '/admin/courses/$courseId/manage'
    | '/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/admin'
    | '/super-admin'
    | '/confirm'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/sign-up-success'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/learning-paths'
    | '/my-courses'
    | '/onboarding'
    | '/redeem-code'
    | '/academies/$slug'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies'
    | '/courses'
    | '/admin/learning-paths'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/super-admin/academies'
    | '/super-admin/categories'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/academy/$academySlug/dashboard'
    | '/admin/courses'
    | '/super-admin/gamification'
    | '/academy/$academySlug/courses'
    | '/academy/$academySlug/courses/$courseSlug/assignments'
    | '/academy/$academySlug/courses/$courseSlug/certificates'
    | '/academy/$academySlug/courses/$courseSlug/exams'
    | '/academy/$academySlug/courses/$courseSlug/info'
    | '/academy/$academySlug/courses/$courseSlug/lessons'
    | '/academy/$academySlug/courses/$courseSlug/settings'
    | '/academy/$academySlug/courses/$courseSlug/students'
    | '/super-admin/gamification/academies/$slug/badges'
    | '/academy/$academySlug/courses/$courseSlug'
    | '/admin/courses/$courseId/manage'
    | '/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/_authenticated/admin'
    | '/_authenticated/settings'
    | '/_authenticated/super-admin'
    | '/(auth)/confirm'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/sign-up-success'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/learning-paths'
    | '/_authenticated/my-courses'
    | '/_authenticated/onboarding'
    | '/_authenticated/redeem-code'
    | '/academies/$slug'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies/'
    | '/courses/'
    | '/_authenticated/admin/learning-paths'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/super-admin/academies'
    | '/_authenticated/super-admin/categories'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/academy/$academySlug/dashboard'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/super-admin/gamification/'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug'
    | '/_authenticated/academy/$academySlug/courses/'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/assignments'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/certificates'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/exams'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/info'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/lessons'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/settings'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/students'
    | '/_authenticated/super-admin/gamification/academies/$slug/badges'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/'
    | '/_authenticated/admin/courses/$courseId/manage/'
    | '/_authenticated/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademySelectionRoute: typeof AcademySelectionRoute
  CreateAcademyRoute: typeof CreateAcademyRoute
  LandingRoute: typeof LandingRoute
  authConfirmRoute: typeof authConfirmRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authSignUpSuccessRoute: typeof authSignUpSuccessRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AcademiesSlugRoute: typeof AcademiesSlugRoute
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  PublicCoursesRoute: typeof PublicCoursesRouteWithChildren
  AcademiesIndexRoute: typeof AcademiesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PublicAcademiesAcademySlugRoute: typeof PublicAcademiesAcademySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-academy': {
      id: '/create-academy'
      path: '/create-academy'
      fullPath: '/create-academy'
      preLoaderRoute: typeof CreateAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy-selection': {
      id: '/academy-selection'
      path: '/academy-selection'
      fullPath: '/academy-selection'
      preLoaderRoute: typeof AcademySelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/': {
      id: '/academies/'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/courses': {
      id: '/public/courses'
      path: '/public/courses'
      fullPath: '/public/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/$slug': {
      id: '/academies/$slug'
      path: '/academies/$slug'
      fullPath: '/academies/$slug'
      preLoaderRoute: typeof AcademiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/redeem-code': {
      id: '/_authenticated/redeem-code'
      path: '/redeem-code'
      fullPath: '/redeem-code'
      preLoaderRoute: typeof AuthenticatedRedeemCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-paths': {
      id: '/_authenticated/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof AuthenticatedLearningPathsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up-success': {
      id: '/(auth)/sign-up-success'
      path: '/sign-up-success'
      fullPath: '/sign-up-success'
      preLoaderRoute: typeof authSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirm': {
      id: '/(auth)/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof authConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin': {
      id: '/_authenticated/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedSuperAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/public/courses/$courseSlug': {
      id: '/public/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/public/courses/$courseSlug'
      preLoaderRoute: typeof PublicCoursesCourseSlugRouteImport
      parentRoute: typeof PublicCoursesRoute
    }
    '/public/academies/$academySlug': {
      id: '/public/academies/$academySlug'
      path: '/public/academies/$academySlug'
      fullPath: '/public/academies/$academySlug'
      preLoaderRoute: typeof PublicAcademiesAcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/super-admin/categories': {
      id: '/_authenticated/super-admin/categories'
      path: '/categories'
      fullPath: '/super-admin/categories'
      preLoaderRoute: typeof AuthenticatedSuperAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/super-admin/academies': {
      id: '/_authenticated/super-admin/academies'
      path: '/academies'
      fullPath: '/super-admin/academies'
      preLoaderRoute: typeof AuthenticatedSuperAdminAcademiesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/learning-paths': {
      id: '/_authenticated/admin/learning-paths'
      path: '/learning-paths'
      fullPath: '/admin/learning-paths'
      preLoaderRoute: typeof AuthenticatedAdminLearningPathsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/super-admin/gamification/': {
      id: '/_authenticated/super-admin/gamification/'
      path: '/gamification'
      fullPath: '/super-admin/gamification'
      preLoaderRoute: typeof AuthenticatedSuperAdminGamificationIndexRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/academy/$academySlug/dashboard': {
      id: '/_authenticated/academy/$academySlug/dashboard'
      path: '/academy/$academySlug/dashboard'
      fullPath: '/academy/$academySlug/dashboard'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/': {
      id: '/_authenticated/academy/$academySlug/courses/'
      path: '/academy/$academySlug/courses'
      fullPath: '/academy/$academySlug/courses'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug'
      path: '/academy/$academySlug/courses/$courseSlug'
      fullPath: '/academy/$academySlug/courses/$courseSlug'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses/$courseId/manage/': {
      id: '/_authenticated/admin/courses/$courseId/manage/'
      path: '/courses/$courseId/manage'
      fullPath: '/admin/courses/$courseId/manage'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdManageIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/'
      path: '/'
      fullPath: '/academy/$academySlug/courses/$courseSlug/'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/super-admin/gamification/academies/$slug/badges': {
      id: '/_authenticated/super-admin/gamification/academies/$slug/badges'
      path: '/gamification/academies/$slug/badges'
      fullPath: '/super-admin/gamification/academies/$slug/badges'
      preLoaderRoute: typeof AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRouteImport
      parentRoute: typeof AuthenticatedSuperAdminRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/students': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/students'
      path: '/students'
      fullPath: '/academy/$academySlug/courses/$courseSlug/students'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/settings': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/settings'
      path: '/settings'
      fullPath: '/academy/$academySlug/courses/$courseSlug/settings'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/lessons': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/lessons'
      path: '/lessons'
      fullPath: '/academy/$academySlug/courses/$courseSlug/lessons'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/info': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/info'
      path: '/info'
      fullPath: '/academy/$academySlug/courses/$courseSlug/info'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/exams': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/exams'
      path: '/exams'
      fullPath: '/academy/$academySlug/courses/$courseSlug/exams'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/certificates': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/certificates'
      path: '/certificates'
      fullPath: '/academy/$academySlug/courses/$courseSlug/certificates'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/assignments': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/assignments'
      path: '/assignments'
      fullPath: '/academy/$academySlug/courses/$courseSlug/assignments'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
    '/_authenticated/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions/': {
      id: '/_authenticated/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions/'
      path: '/assessments/$assessmentId/questions'
      fullPath: '/academy/$academySlug/courses/$courseSlug/assessments/$assessmentId/questions'
      preLoaderRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminLearningPathsRoute: typeof AuthenticatedAdminLearningPathsRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
  AuthenticatedAdminCoursesCourseIdManageIndexRoute: typeof AuthenticatedAdminCoursesCourseIdManageIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminLearningPathsRoute: AuthenticatedAdminLearningPathsRoute,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
    AuthenticatedAdminCoursesCourseIdManageIndexRoute:
      AuthenticatedAdminCoursesCourseIdManageIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedSuperAdminRouteRouteChildren {
  AuthenticatedSuperAdminAcademiesRoute: typeof AuthenticatedSuperAdminAcademiesRoute
  AuthenticatedSuperAdminCategoriesRoute: typeof AuthenticatedSuperAdminCategoriesRoute
  AuthenticatedSuperAdminGamificationIndexRoute: typeof AuthenticatedSuperAdminGamificationIndexRoute
  AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute: typeof AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute
}

const AuthenticatedSuperAdminRouteRouteChildren: AuthenticatedSuperAdminRouteRouteChildren =
  {
    AuthenticatedSuperAdminAcademiesRoute:
      AuthenticatedSuperAdminAcademiesRoute,
    AuthenticatedSuperAdminCategoriesRoute:
      AuthenticatedSuperAdminCategoriesRoute,
    AuthenticatedSuperAdminGamificationIndexRoute:
      AuthenticatedSuperAdminGamificationIndexRoute,
    AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute:
      AuthenticatedSuperAdminGamificationAcademiesSlugBadgesRoute,
  }

const AuthenticatedSuperAdminRouteRouteWithChildren =
  AuthenticatedSuperAdminRouteRoute._addFileChildren(
    AuthenticatedSuperAdminRouteRouteChildren,
  )

interface AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteChildren {
  AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute
}

const AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteChildren: AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteChildren =
  {
    AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugAssignmentsRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugCertificatesRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugExamsRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugInfoRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugLessonsRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugSettingsRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugStudentsRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugIndexRoute,
    AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute:
      AuthenticatedAcademyAcademySlugCoursesCourseSlugAssessmentsAssessmentIdQuestionsIndexRoute,
  }

const AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteWithChildren =
  AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute._addFileChildren(
    AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedSuperAdminRouteRoute: typeof AuthenticatedSuperAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearningPathsRoute: typeof AuthenticatedLearningPathsRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRedeemCodeRoute: typeof AuthenticatedRedeemCodeRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAcademyAcademySlugDashboardRoute: typeof AuthenticatedAcademyAcademySlugDashboardRoute
  AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute: typeof AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteWithChildren
  AuthenticatedAcademyAcademySlugCoursesIndexRoute: typeof AuthenticatedAcademyAcademySlugCoursesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedSuperAdminRouteRoute:
    AuthenticatedSuperAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearningPathsRoute: AuthenticatedLearningPathsRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRedeemCodeRoute: AuthenticatedRedeemCodeRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAcademyAcademySlugDashboardRoute:
    AuthenticatedAcademyAcademySlugDashboardRoute,
  AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRoute:
    AuthenticatedAcademyAcademySlugCoursesCourseSlugRouteRouteWithChildren,
  AuthenticatedAcademyAcademySlugCoursesIndexRoute:
    AuthenticatedAcademyAcademySlugCoursesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicCoursesRouteChildren {
  PublicCoursesCourseSlugRoute: typeof PublicCoursesCourseSlugRoute
}

const PublicCoursesRouteChildren: PublicCoursesRouteChildren = {
  PublicCoursesCourseSlugRoute: PublicCoursesCourseSlugRoute,
}

const PublicCoursesRouteWithChildren = PublicCoursesRoute._addFileChildren(
  PublicCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademySelectionRoute: AcademySelectionRoute,
  CreateAcademyRoute: CreateAcademyRoute,
  LandingRoute: LandingRoute,
  authConfirmRoute: authConfirmRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authSignUpSuccessRoute: authSignUpSuccessRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AcademiesSlugRoute: AcademiesSlugRoute,
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  PublicCoursesRoute: PublicCoursesRouteWithChildren,
  AcademiesIndexRoute: AcademiesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PublicAcademiesAcademySlugRoute: PublicAcademiesAcademySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
