/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as CreateAcademyRouteImport } from './routes/create-academy'
import { Route as AcademySelectionRouteImport } from './routes/academy-selection'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as AcademiesIndexRouteImport } from './routes/academies/index'
import { Route as PublicCoursesRouteImport } from './routes/public/courses'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses/$courseSlug'
import { Route as AcademyAcademyIdRouteImport } from './routes/academy/$academyId'
import { Route as AcademiesSlugRouteImport } from './routes/academies/$slug'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpSuccessRouteImport } from './routes/(auth)/sign-up-success'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authConfirmRouteImport } from './routes/(auth)/confirm'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as PublicCoursesCourseSlugRouteImport } from './routes/public/courses/$courseSlug'
import { Route as PublicAcademiesAcademySlugRouteImport } from './routes/public/academies/$academySlug'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AcademyAcademyIdTeachingRouteImport } from './routes/academy/$academyId/teaching'
import { Route as AcademyAcademyIdStudentsRouteImport } from './routes/academy/$academyId/students'
import { Route as AcademyAcademyIdSettingsRouteImport } from './routes/academy/$academyId/settings'
import { Route as AcademyAcademyIdReportsRouteImport } from './routes/academy/$academyId/reports'
import { Route as AcademyAcademyIdProfileRouteImport } from './routes/academy/$academyId/profile'
import { Route as AcademyAcademyIdNotificationsRouteImport } from './routes/academy/$academyId/notifications'
import { Route as AcademyAcademyIdMessagesRouteImport } from './routes/academy/$academyId/messages'
import { Route as AcademyAcademyIdDisplayRouteImport } from './routes/academy/$academyId/display'
import { Route as AcademyAcademyIdDashboardRouteImport } from './routes/academy/$academyId/dashboard'
import { Route as AcademyAcademyIdCoursesRouteImport } from './routes/academy/$academyId/courses'
import { Route as AcademyAcademyIdCalendarRouteImport } from './routes/academy/$academyId/calendar'
import { Route as AcademyAcademyIdAppearanceRouteImport } from './routes/academy/$academyId/appearance'
import { Route as AcademyAcademyIdAnalyticsRouteImport } from './routes/academy/$academyId/analytics'
import { Route as AcademyAcademyIdAchievementsRouteImport } from './routes/academy/$academyId/achievements'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AcademyAcademyIdTeachingGradesRouteImport } from './routes/academy/$academyId/teaching/grades'
import { Route as AcademyAcademyIdTeachingCoursesRouteImport } from './routes/academy/$academyId/teaching/courses'
import { Route as AcademyAcademyIdTeachingAssignmentsRouteImport } from './routes/academy/$academyId/teaching/assignments'

const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAcademyRoute = CreateAcademyRouteImport.update({
  id: '/create-academy',
  path: '/create-academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademySelectionRoute = AcademySelectionRouteImport.update({
  id: '/academy-selection',
  path: '/academy-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesIndexRoute = AcademiesIndexRouteImport.update({
  id: '/academies/',
  path: '/academies/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/public/courses',
  path: '/public/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/courses/$courseSlug',
  path: '/courses/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyAcademyIdRoute = AcademyAcademyIdRouteImport.update({
  id: '/academy/$academyId',
  path: '/academy/$academyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiesSlugRoute = AcademiesSlugRouteImport.update({
  id: '/academies/$slug',
  path: '/academies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpSuccessRoute = authSignUpSuccessRouteImport.update({
  id: '/(auth)/sign-up-success',
  path: '/sign-up-success',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authConfirmRoute = authConfirmRouteImport.update({
  id: '/(auth)/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicCoursesCourseSlugRoute = PublicCoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => PublicCoursesRoute,
} as any)
const PublicAcademiesAcademySlugRoute =
  PublicAcademiesAcademySlugRouteImport.update({
    id: '/public/academies/$academySlug',
    path: '/public/academies/$academySlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AcademyAcademyIdTeachingRoute =
  AcademyAcademyIdTeachingRouteImport.update({
    id: '/teaching',
    path: '/teaching',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdStudentsRoute =
  AcademyAcademyIdStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdSettingsRoute =
  AcademyAcademyIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdReportsRoute = AcademyAcademyIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AcademyAcademyIdRoute,
} as any)
const AcademyAcademyIdProfileRoute = AcademyAcademyIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AcademyAcademyIdRoute,
} as any)
const AcademyAcademyIdNotificationsRoute =
  AcademyAcademyIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdMessagesRoute =
  AcademyAcademyIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdDisplayRoute = AcademyAcademyIdDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => AcademyAcademyIdRoute,
} as any)
const AcademyAcademyIdDashboardRoute =
  AcademyAcademyIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdCoursesRoute = AcademyAcademyIdCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AcademyAcademyIdRoute,
} as any)
const AcademyAcademyIdCalendarRoute =
  AcademyAcademyIdCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdAppearanceRoute =
  AcademyAcademyIdAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdAnalyticsRoute =
  AcademyAcademyIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AcademyAcademyIdAchievementsRoute =
  AcademyAcademyIdAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AcademyAcademyIdRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AcademyAcademyIdTeachingGradesRoute =
  AcademyAcademyIdTeachingGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AcademyAcademyIdTeachingRoute,
  } as any)
const AcademyAcademyIdTeachingCoursesRoute =
  AcademyAcademyIdTeachingCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AcademyAcademyIdTeachingRoute,
  } as any)
const AcademyAcademyIdTeachingAssignmentsRoute =
  AcademyAcademyIdTeachingAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AcademyAcademyIdTeachingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/academy/$academyId': typeof AcademyAcademyIdRouteWithChildren
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies': typeof AcademiesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/academy/$academyId/achievements': typeof AcademyAcademyIdAchievementsRoute
  '/academy/$academyId/analytics': typeof AcademyAcademyIdAnalyticsRoute
  '/academy/$academyId/appearance': typeof AcademyAcademyIdAppearanceRoute
  '/academy/$academyId/calendar': typeof AcademyAcademyIdCalendarRoute
  '/academy/$academyId/courses': typeof AcademyAcademyIdCoursesRoute
  '/academy/$academyId/dashboard': typeof AcademyAcademyIdDashboardRoute
  '/academy/$academyId/display': typeof AcademyAcademyIdDisplayRoute
  '/academy/$academyId/messages': typeof AcademyAcademyIdMessagesRoute
  '/academy/$academyId/notifications': typeof AcademyAcademyIdNotificationsRoute
  '/academy/$academyId/profile': typeof AcademyAcademyIdProfileRoute
  '/academy/$academyId/reports': typeof AcademyAcademyIdReportsRoute
  '/academy/$academyId/settings': typeof AcademyAcademyIdSettingsRoute
  '/academy/$academyId/students': typeof AcademyAcademyIdStudentsRoute
  '/academy/$academyId/teaching': typeof AcademyAcademyIdTeachingRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academy/$academyId/teaching/assignments': typeof AcademyAcademyIdTeachingAssignmentsRoute
  '/academy/$academyId/teaching/courses': typeof AcademyAcademyIdTeachingCoursesRoute
  '/academy/$academyId/teaching/grades': typeof AcademyAcademyIdTeachingGradesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/confirm': typeof authConfirmRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/sign-up-success': typeof authSignUpSuccessRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/academy/$academyId': typeof AcademyAcademyIdRouteWithChildren
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies': typeof AcademiesIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/academy/$academyId/achievements': typeof AcademyAcademyIdAchievementsRoute
  '/academy/$academyId/analytics': typeof AcademyAcademyIdAnalyticsRoute
  '/academy/$academyId/appearance': typeof AcademyAcademyIdAppearanceRoute
  '/academy/$academyId/calendar': typeof AcademyAcademyIdCalendarRoute
  '/academy/$academyId/courses': typeof AcademyAcademyIdCoursesRoute
  '/academy/$academyId/dashboard': typeof AcademyAcademyIdDashboardRoute
  '/academy/$academyId/display': typeof AcademyAcademyIdDisplayRoute
  '/academy/$academyId/messages': typeof AcademyAcademyIdMessagesRoute
  '/academy/$academyId/notifications': typeof AcademyAcademyIdNotificationsRoute
  '/academy/$academyId/profile': typeof AcademyAcademyIdProfileRoute
  '/academy/$academyId/reports': typeof AcademyAcademyIdReportsRoute
  '/academy/$academyId/settings': typeof AcademyAcademyIdSettingsRoute
  '/academy/$academyId/students': typeof AcademyAcademyIdStudentsRoute
  '/academy/$academyId/teaching': typeof AcademyAcademyIdTeachingRouteWithChildren
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/academy/$academyId/teaching/assignments': typeof AcademyAcademyIdTeachingAssignmentsRoute
  '/academy/$academyId/teaching/courses': typeof AcademyAcademyIdTeachingCoursesRoute
  '/academy/$academyId/teaching/grades': typeof AcademyAcademyIdTeachingGradesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/academy-selection': typeof AcademySelectionRoute
  '/create-academy': typeof CreateAcademyRoute
  '/landing': typeof LandingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/confirm': typeof authConfirmRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/sign-up-success': typeof authSignUpSuccessRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/academies/$slug': typeof AcademiesSlugRoute
  '/academy/$academyId': typeof AcademyAcademyIdRouteWithChildren
  '/courses/$courseSlug': typeof CoursesCourseSlugRoute
  '/public/courses': typeof PublicCoursesRouteWithChildren
  '/academies/': typeof AcademiesIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/academy/$academyId/achievements': typeof AcademyAcademyIdAchievementsRoute
  '/academy/$academyId/analytics': typeof AcademyAcademyIdAnalyticsRoute
  '/academy/$academyId/appearance': typeof AcademyAcademyIdAppearanceRoute
  '/academy/$academyId/calendar': typeof AcademyAcademyIdCalendarRoute
  '/academy/$academyId/courses': typeof AcademyAcademyIdCoursesRoute
  '/academy/$academyId/dashboard': typeof AcademyAcademyIdDashboardRoute
  '/academy/$academyId/display': typeof AcademyAcademyIdDisplayRoute
  '/academy/$academyId/messages': typeof AcademyAcademyIdMessagesRoute
  '/academy/$academyId/notifications': typeof AcademyAcademyIdNotificationsRoute
  '/academy/$academyId/profile': typeof AcademyAcademyIdProfileRoute
  '/academy/$academyId/reports': typeof AcademyAcademyIdReportsRoute
  '/academy/$academyId/settings': typeof AcademyAcademyIdSettingsRoute
  '/academy/$academyId/students': typeof AcademyAcademyIdStudentsRoute
  '/academy/$academyId/teaching': typeof AcademyAcademyIdTeachingRouteWithChildren
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/public/academies/$academySlug': typeof PublicAcademiesAcademySlugRoute
  '/public/courses/$courseSlug': typeof PublicCoursesCourseSlugRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/academy/$academyId/teaching/assignments': typeof AcademyAcademyIdTeachingAssignmentsRoute
  '/academy/$academyId/teaching/courses': typeof AcademyAcademyIdTeachingCoursesRoute
  '/academy/$academyId/teaching/grades': typeof AcademyAcademyIdTeachingGradesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/settings'
    | '/clerk/'
    | '/confirm'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/sign-up-success'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/onboarding'
    | '/academies/$slug'
    | '/academy/$academyId'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies'
    | '/courses'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/academy/$academyId/achievements'
    | '/academy/$academyId/analytics'
    | '/academy/$academyId/appearance'
    | '/academy/$academyId/calendar'
    | '/academy/$academyId/courses'
    | '/academy/$academyId/dashboard'
    | '/academy/$academyId/display'
    | '/academy/$academyId/messages'
    | '/academy/$academyId/notifications'
    | '/academy/$academyId/profile'
    | '/academy/$academyId/reports'
    | '/academy/$academyId/settings'
    | '/academy/$academyId/students'
    | '/academy/$academyId/teaching'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/academy/$academyId/teaching/assignments'
    | '/academy/$academyId/teaching/courses'
    | '/academy/$academyId/teaching/grades'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/clerk'
    | '/confirm'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/sign-up-success'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/dashboard'
    | '/onboarding'
    | '/academies/$slug'
    | '/academy/$academyId'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies'
    | '/courses'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/academy/$academyId/achievements'
    | '/academy/$academyId/analytics'
    | '/academy/$academyId/appearance'
    | '/academy/$academyId/calendar'
    | '/academy/$academyId/courses'
    | '/academy/$academyId/dashboard'
    | '/academy/$academyId/display'
    | '/academy/$academyId/messages'
    | '/academy/$academyId/notifications'
    | '/academy/$academyId/profile'
    | '/academy/$academyId/reports'
    | '/academy/$academyId/settings'
    | '/academy/$academyId/students'
    | '/academy/$academyId/teaching'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/academy/$academyId/teaching/assignments'
    | '/academy/$academyId/teaching/courses'
    | '/academy/$academyId/teaching/grades'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/clerk'
    | '/academy-selection'
    | '/create-academy'
    | '/landing'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/confirm'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/sign-up-success'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/academies/$slug'
    | '/academy/$academyId'
    | '/courses/$courseSlug'
    | '/public/courses'
    | '/academies/'
    | '/courses/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/academy/$academyId/achievements'
    | '/academy/$academyId/analytics'
    | '/academy/$academyId/appearance'
    | '/academy/$academyId/calendar'
    | '/academy/$academyId/courses'
    | '/academy/$academyId/dashboard'
    | '/academy/$academyId/display'
    | '/academy/$academyId/messages'
    | '/academy/$academyId/notifications'
    | '/academy/$academyId/profile'
    | '/academy/$academyId/reports'
    | '/academy/$academyId/settings'
    | '/academy/$academyId/students'
    | '/academy/$academyId/teaching'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/public/academies/$academySlug'
    | '/public/courses/$courseSlug'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/academy/$academyId/teaching/assignments'
    | '/academy/$academyId/teaching/courses'
    | '/academy/$academyId/teaching/grades'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  AcademySelectionRoute: typeof AcademySelectionRoute
  CreateAcademyRoute: typeof CreateAcademyRoute
  LandingRoute: typeof LandingRoute
  authConfirmRoute: typeof authConfirmRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  authSignUpSuccessRoute: typeof authSignUpSuccessRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AcademiesSlugRoute: typeof AcademiesSlugRoute
  AcademyAcademyIdRoute: typeof AcademyAcademyIdRouteWithChildren
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRoute
  PublicCoursesRoute: typeof PublicCoursesRouteWithChildren
  AcademiesIndexRoute: typeof AcademiesIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  PublicAcademiesAcademySlugRoute: typeof PublicAcademiesAcademySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-academy': {
      id: '/create-academy'
      path: '/create-academy'
      fullPath: '/create-academy'
      preLoaderRoute: typeof CreateAcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy-selection': {
      id: '/academy-selection'
      path: '/academy-selection'
      fullPath: '/academy-selection'
      preLoaderRoute: typeof AcademySelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/': {
      id: '/academies/'
      path: '/academies'
      fullPath: '/academies'
      preLoaderRoute: typeof AcademiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/courses': {
      id: '/public/courses'
      path: '/public/courses'
      fullPath: '/public/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$academyId': {
      id: '/academy/$academyId'
      path: '/academy/$academyId'
      fullPath: '/academy/$academyId'
      preLoaderRoute: typeof AcademyAcademyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academies/$slug': {
      id: '/academies/$slug'
      path: '/academies/$slug'
      fullPath: '/academies/$slug'
      preLoaderRoute: typeof AcademiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up-success': {
      id: '/(auth)/sign-up-success'
      path: '/sign-up-success'
      fullPath: '/sign-up-success'
      preLoaderRoute: typeof authSignUpSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/confirm': {
      id: '/(auth)/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof authConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/public/courses/$courseSlug': {
      id: '/public/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/public/courses/$courseSlug'
      preLoaderRoute: typeof PublicCoursesCourseSlugRouteImport
      parentRoute: typeof PublicCoursesRoute
    }
    '/public/academies/$academySlug': {
      id: '/public/academies/$academySlug'
      path: '/public/academies/$academySlug'
      fullPath: '/public/academies/$academySlug'
      preLoaderRoute: typeof PublicAcademiesAcademySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/academy/$academyId/teaching': {
      id: '/academy/$academyId/teaching'
      path: '/teaching'
      fullPath: '/academy/$academyId/teaching'
      preLoaderRoute: typeof AcademyAcademyIdTeachingRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/students': {
      id: '/academy/$academyId/students'
      path: '/students'
      fullPath: '/academy/$academyId/students'
      preLoaderRoute: typeof AcademyAcademyIdStudentsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/settings': {
      id: '/academy/$academyId/settings'
      path: '/settings'
      fullPath: '/academy/$academyId/settings'
      preLoaderRoute: typeof AcademyAcademyIdSettingsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/reports': {
      id: '/academy/$academyId/reports'
      path: '/reports'
      fullPath: '/academy/$academyId/reports'
      preLoaderRoute: typeof AcademyAcademyIdReportsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/profile': {
      id: '/academy/$academyId/profile'
      path: '/profile'
      fullPath: '/academy/$academyId/profile'
      preLoaderRoute: typeof AcademyAcademyIdProfileRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/notifications': {
      id: '/academy/$academyId/notifications'
      path: '/notifications'
      fullPath: '/academy/$academyId/notifications'
      preLoaderRoute: typeof AcademyAcademyIdNotificationsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/messages': {
      id: '/academy/$academyId/messages'
      path: '/messages'
      fullPath: '/academy/$academyId/messages'
      preLoaderRoute: typeof AcademyAcademyIdMessagesRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/display': {
      id: '/academy/$academyId/display'
      path: '/display'
      fullPath: '/academy/$academyId/display'
      preLoaderRoute: typeof AcademyAcademyIdDisplayRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/dashboard': {
      id: '/academy/$academyId/dashboard'
      path: '/dashboard'
      fullPath: '/academy/$academyId/dashboard'
      preLoaderRoute: typeof AcademyAcademyIdDashboardRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/courses': {
      id: '/academy/$academyId/courses'
      path: '/courses'
      fullPath: '/academy/$academyId/courses'
      preLoaderRoute: typeof AcademyAcademyIdCoursesRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/calendar': {
      id: '/academy/$academyId/calendar'
      path: '/calendar'
      fullPath: '/academy/$academyId/calendar'
      preLoaderRoute: typeof AcademyAcademyIdCalendarRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/appearance': {
      id: '/academy/$academyId/appearance'
      path: '/appearance'
      fullPath: '/academy/$academyId/appearance'
      preLoaderRoute: typeof AcademyAcademyIdAppearanceRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/analytics': {
      id: '/academy/$academyId/analytics'
      path: '/analytics'
      fullPath: '/academy/$academyId/analytics'
      preLoaderRoute: typeof AcademyAcademyIdAnalyticsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/academy/$academyId/achievements': {
      id: '/academy/$academyId/achievements'
      path: '/achievements'
      fullPath: '/academy/$academyId/achievements'
      preLoaderRoute: typeof AcademyAcademyIdAchievementsRouteImport
      parentRoute: typeof AcademyAcademyIdRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/academy/$academyId/teaching/grades': {
      id: '/academy/$academyId/teaching/grades'
      path: '/grades'
      fullPath: '/academy/$academyId/teaching/grades'
      preLoaderRoute: typeof AcademyAcademyIdTeachingGradesRouteImport
      parentRoute: typeof AcademyAcademyIdTeachingRoute
    }
    '/academy/$academyId/teaching/courses': {
      id: '/academy/$academyId/teaching/courses'
      path: '/courses'
      fullPath: '/academy/$academyId/teaching/courses'
      preLoaderRoute: typeof AcademyAcademyIdTeachingCoursesRouteImport
      parentRoute: typeof AcademyAcademyIdTeachingRoute
    }
    '/academy/$academyId/teaching/assignments': {
      id: '/academy/$academyId/teaching/assignments'
      path: '/assignments'
      fullPath: '/academy/$academyId/teaching/assignments'
      preLoaderRoute: typeof AcademyAcademyIdTeachingAssignmentsRouteImport
      parentRoute: typeof AcademyAcademyIdTeachingRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

interface AcademyAcademyIdTeachingRouteChildren {
  AcademyAcademyIdTeachingAssignmentsRoute: typeof AcademyAcademyIdTeachingAssignmentsRoute
  AcademyAcademyIdTeachingCoursesRoute: typeof AcademyAcademyIdTeachingCoursesRoute
  AcademyAcademyIdTeachingGradesRoute: typeof AcademyAcademyIdTeachingGradesRoute
}

const AcademyAcademyIdTeachingRouteChildren: AcademyAcademyIdTeachingRouteChildren =
  {
    AcademyAcademyIdTeachingAssignmentsRoute:
      AcademyAcademyIdTeachingAssignmentsRoute,
    AcademyAcademyIdTeachingCoursesRoute: AcademyAcademyIdTeachingCoursesRoute,
    AcademyAcademyIdTeachingGradesRoute: AcademyAcademyIdTeachingGradesRoute,
  }

const AcademyAcademyIdTeachingRouteWithChildren =
  AcademyAcademyIdTeachingRoute._addFileChildren(
    AcademyAcademyIdTeachingRouteChildren,
  )

interface AcademyAcademyIdRouteChildren {
  AcademyAcademyIdAchievementsRoute: typeof AcademyAcademyIdAchievementsRoute
  AcademyAcademyIdAnalyticsRoute: typeof AcademyAcademyIdAnalyticsRoute
  AcademyAcademyIdAppearanceRoute: typeof AcademyAcademyIdAppearanceRoute
  AcademyAcademyIdCalendarRoute: typeof AcademyAcademyIdCalendarRoute
  AcademyAcademyIdCoursesRoute: typeof AcademyAcademyIdCoursesRoute
  AcademyAcademyIdDashboardRoute: typeof AcademyAcademyIdDashboardRoute
  AcademyAcademyIdDisplayRoute: typeof AcademyAcademyIdDisplayRoute
  AcademyAcademyIdMessagesRoute: typeof AcademyAcademyIdMessagesRoute
  AcademyAcademyIdNotificationsRoute: typeof AcademyAcademyIdNotificationsRoute
  AcademyAcademyIdProfileRoute: typeof AcademyAcademyIdProfileRoute
  AcademyAcademyIdReportsRoute: typeof AcademyAcademyIdReportsRoute
  AcademyAcademyIdSettingsRoute: typeof AcademyAcademyIdSettingsRoute
  AcademyAcademyIdStudentsRoute: typeof AcademyAcademyIdStudentsRoute
  AcademyAcademyIdTeachingRoute: typeof AcademyAcademyIdTeachingRouteWithChildren
}

const AcademyAcademyIdRouteChildren: AcademyAcademyIdRouteChildren = {
  AcademyAcademyIdAchievementsRoute: AcademyAcademyIdAchievementsRoute,
  AcademyAcademyIdAnalyticsRoute: AcademyAcademyIdAnalyticsRoute,
  AcademyAcademyIdAppearanceRoute: AcademyAcademyIdAppearanceRoute,
  AcademyAcademyIdCalendarRoute: AcademyAcademyIdCalendarRoute,
  AcademyAcademyIdCoursesRoute: AcademyAcademyIdCoursesRoute,
  AcademyAcademyIdDashboardRoute: AcademyAcademyIdDashboardRoute,
  AcademyAcademyIdDisplayRoute: AcademyAcademyIdDisplayRoute,
  AcademyAcademyIdMessagesRoute: AcademyAcademyIdMessagesRoute,
  AcademyAcademyIdNotificationsRoute: AcademyAcademyIdNotificationsRoute,
  AcademyAcademyIdProfileRoute: AcademyAcademyIdProfileRoute,
  AcademyAcademyIdReportsRoute: AcademyAcademyIdReportsRoute,
  AcademyAcademyIdSettingsRoute: AcademyAcademyIdSettingsRoute,
  AcademyAcademyIdStudentsRoute: AcademyAcademyIdStudentsRoute,
  AcademyAcademyIdTeachingRoute: AcademyAcademyIdTeachingRouteWithChildren,
}

const AcademyAcademyIdRouteWithChildren =
  AcademyAcademyIdRoute._addFileChildren(AcademyAcademyIdRouteChildren)

interface PublicCoursesRouteChildren {
  PublicCoursesCourseSlugRoute: typeof PublicCoursesCourseSlugRoute
}

const PublicCoursesRouteChildren: PublicCoursesRouteChildren = {
  PublicCoursesCourseSlugRoute: PublicCoursesCourseSlugRoute,
}

const PublicCoursesRouteWithChildren = PublicCoursesRoute._addFileChildren(
  PublicCoursesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  AcademySelectionRoute: AcademySelectionRoute,
  CreateAcademyRoute: CreateAcademyRoute,
  LandingRoute: LandingRoute,
  authConfirmRoute: authConfirmRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  authSignUpSuccessRoute: authSignUpSuccessRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AcademiesSlugRoute: AcademiesSlugRoute,
  AcademyAcademyIdRoute: AcademyAcademyIdRouteWithChildren,
  CoursesCourseSlugRoute: CoursesCourseSlugRoute,
  PublicCoursesRoute: PublicCoursesRouteWithChildren,
  AcademiesIndexRoute: AcademiesIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  PublicAcademiesAcademySlugRoute: PublicAcademiesAcademySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
